# Docker Compose build file: docker-compose -f build.yml build
version: "3.7"

x-common-args: &common-args
  PIHOLE_VERSION: ${PIHOLE_VERSION}
  PIHOLE_TAG: ${PIHOLE_TAG}
  CORE_VERSION: ${CORE_VERSION}
  WEB_VERSION: ${WEB_VERSION}
  FTL_VERSION: ${FTL_VERSION}
  NAME: pihole/pihole
  MAINTAINER: adam@diginc.us

services:
  amd64:
    image: pihole:${PIHOLE_VERSION}-amd64-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-base:${DEBIAN_VERSION:-buster}
        PIHOLE_ARCH: amd64
  armel:
    image: pihole:${PIHOLE_VERSION}-armel-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:armel-${DEBIAN_VERSION:-buster}-slim
        PIHOLE_ARCH: armel
  armhf:
    image: pihole:${PIHOLE_VERSION}-armhf-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:armhf-${DEBIAN_VERSION:-buster}-slim
        PIHOLE_ARCH: arm
  arm64:
    image: pihole:${PIHOLE_VERSION}-arm64-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:arm64-${DEBIAN_VERSION:-buster}-slim
        PIHOLE_ARCH: arm64
  i386:
    image: pihole:${PIHOLE_VERSION}-i386-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:i386-${DEBIAN_VERSION:-buster}-slim
        PIHOLE_ARCH: i386
